
name: Windows RDP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Chocolatey
        run: choco install rdp
      - name: Create RDP file
        run: rdp /f /u <username> /p <password> /t 0 /v <server_address> > windows-rdp.rdp
      - name: Upload RDP file
        uses: actions/upload-artifact@v1
        with:
          name: windows-rdp
          path: windows-rdp.rdp
